language: objective-c
osx_image: xcode8

branches:
 only:
 - master
 - develop

xcode_project: ImageAsyncTest.xcodeproj
xcode_scheme: YNImageAsyncTests

script:
- xcodebuild clean build test -project YNImageAsyncTest.xcodeproj -scheme YNImageAsyncTests
