language: objective-c
osx_image: xcode8

branches:
 only:
 - master
 - develop

xcode_project: ImageAsyncTest.xcodeproj
xcode_scheme: YNImageAsyncTests

script:
- echo Build demo apps
- xcodebuild clean build test -project ImageAsyncTest.xcodeproj -scheme 'Demo' -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.0'
